const $ = s => document.querySelector(s);
const products = [
  {id:'reset',title:'The 30-Day Reset',category:'FOR A CLEARER HEAD',kind:['reset','everyday'],price:599,image:'assets/reset-screwpost.jpg',badge:'30 PAGES / REFILLABLE',short:'A slim, reusable home for a clearer month.',description:'A minimal, slightly quirky 30-page monthly journal concept for young professionals. Two brass screw posts let you insert fresh pages whenever you need another month. The tiny wavering line on its cover straightens out: a quieter visual metaphor for thinking clearly.',notes:['Slim 30-page starter journal with two screw posts','Reusable cover; proposed monthly refill pack ₹149','Illustrative starter price ₹599 — not a live SKU']},
  {id:'parent',title:'Little Beginnings',category:'FOR NEW PARENTS',kind:['parents'],price:799,image:'assets/parent-keepsake.jpg',badge:'NEW PARENT CONCEPT',short:'Keep all the little firsts close.',description:'A proposed keepsake collection for new parents. Warm illustration, a little softness, and a place for first words, quiet moments and the days that go by too fast.',notes:['Original parent-and-baby cover illustration','Milestone-inspired journal concept','Price shown is illustrative']},
  {id:'breakfast',title:'The Breakfast Planner',category:'FOR YOUR MORNINGS',kind:['everyday'],price:699,image:'assets/product-breakfast.jpg',badge:'PROPOSED CONCEPT',short:'Your morning plan, with a side of personality.',description:'A proposed sandwich-shaped planner for a breakfast-table ritual: a first sip, your top three priorities, and a gentler beginning before the first scroll.',notes:['Sandwich-inspired die-cut cover concept','Designed for a top-three morning ritual','Not a product currently for sale'],interest:true},
  {id:'undated',title:'The Open-Ended Journal',category:'FOR EVERY DAY',kind:['reset','everyday'],price:649,image:'assets/product-journal.jpg',badge:'START WHENEVER',short:'No dates. No pressure. Just a place to begin.',description:'An illustrative undated journal direction inspired by EVNOI’s existing stationery range. For notes, thoughts and fresh starts that do not wait for January.',notes:['Undated, start-anytime direction','Illustration-led cover concept','Price shown is illustrative']}
];
const state={filter:'all',query:'',bag:{},favorites:new Set(),slide:0,book:'reset',bookOpen:false,page:0};
const rupees=n=>'₹'+n.toLocaleString('en-IN');
const rail=$('#storyRail');
function scrollStories(direction){const card=rail.querySelector('.story-card');if(card)rail.scrollBy({left:direction*(card.getBoundingClientRect().width+18),behavior:'smooth'})}
$('#storyPrev').addEventListener('click',()=>scrollStories(-1));$('#storyNext').addEventListener('click',()=>scrollStories(1));
function renderProducts(){const matched=products.filter(p=>(state.filter==='all'||p.kind.includes(state.filter))&&(p.title+' '+p.category+' '+p.short).toLowerCase().includes(state.query.toLowerCase()));$('#productGrid').innerHTML=matched.map(p=>`<article class="product-card"><div class="product-image-wrap" data-open="${p.id}" role="button" tabindex="0" aria-label="View ${p.title}"><img src="${p.image}" alt="Illustrative ${p.title} product concept" loading="lazy"><span class="product-badge">${p.badge}</span><button class="heart-btn ${state.favorites.has(p.id)?'liked':''}" data-favorite="${p.id}" aria-label="${state.favorites.has(p.id)?'Remove '+p.title+' from':'Save '+p.title+' to'} favorites" aria-pressed="${state.favorites.has(p.id)}"><svg><use href="#heart"/></svg></button><button class="product-quick" data-open="${p.id}">Explore this piece</button></div><div class="product-info"><span class="product-category">${p.category}</span><div class="product-title-line"><h3>${p.title}</h3><span>${rupees(p.price)}*</span></div><p>${p.short}</p><button class="card-action" data-${p.interest?'interest':'add'}="${p.id}">${p.interest?'Explore concept':'Add to demo bag'} ↗</button></div></article>`).join('');$('#emptyState').hidden=matched.length!==0}
function toast(s){let el=$('#toast');el.textContent=s;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),3000)}
function closeOverlays(){['#bagDrawer','#productModal','#interestModal'].forEach(s=>$(s).hidden=true);$('#scrim').hidden=true;document.body.classList.remove('locked')}
function openOverlay(s){closeOverlays();$(s).hidden=false;$('#scrim').hidden=false;document.body.classList.add('locked');$(s).querySelector('button')?.focus()}
function openProduct(id){let p=products.find(x=>x.id===id);if(!p)return;$('#modalContent').innerHTML=`<img src="${p.image}" alt="${p.title} concept photograph"><div class="modal-details"><span class="kicker">${p.category} / THE EVNOI EDIT</span><h2 id="modalTitle">${p.title}</h2><div class="price">${rupees(p.price)}*</div><p>${p.description}</p><ul>${p.notes.map(x=>`<li>✳ &nbsp; ${x}</li>`).join('')}</ul><button class="btn btn-ink" data-${p.interest?'interest':'add'}="${p.id}">${p.interest?'I’m interested':'Add to demo bag'} <svg><use href="#arrow"/></svg></button><small>*Case-study concept price. No transactions or real orders are processed.</small></div>`;openOverlay('#productModal')}
function renderBag(){let ids=Object.keys(state.bag),count=ids.reduce((a,id)=>a+state.bag[id],0);$('#bagCount').textContent=count;$('#drawerCount').textContent=`(${count})`;$('#bagItems').innerHTML=ids.length?ids.map(id=>{let p=products.find(x=>x.id===id);return `<div class="bag-item"><img src="${p.image}" alt=""><div><strong>${p.title}</strong><span>${rupees(p.price)}* each</span><div class="qty-control"><button data-qty="${id}" data-delta="-1" aria-label="Decrease ${p.title} quantity">−</button><span>${state.bag[id]}</span><button data-qty="${id}" data-delta="1" aria-label="Increase ${p.title} quantity">+</button></div><button class="remove-item" data-remove="${id}">Remove</button></div></div>`}).join(''):`<div class="empty-bag"><span>✳</span><p>Your bag is a blank page.</p><small>Find a little something that feels like you.</small></div>`;$('#subtotal').textContent=rupees(ids.reduce((a,id)=>a+products.find(x=>x.id===id).price*state.bag[id],0))}
function addToBag(id){let p=products.find(x=>x.id===id);if(!p)return;if(p.interest){openOverlay('#interestModal');return}state.bag[id]=(state.bag[id]||0)+1;renderBag();openOverlay('#bagDrawer');toast('Added to your demo bag')}
const bookData={
  reset:{cover:'assets/cover-reset.svg',alt:'The 30-Day Reset cover: digital cables become flowers',label:'EVNOI / THE 30-DAY RESET',caption:'A little room to think.',description:'30 pages. Two screw posts. Another month when you’re ready.',pages:[{title:'A gentler start',intro:'This month, I want to make more room for…',lines:['Something I can let go of','Something I want to feel','One little thing I’ll begin']},{title:'Today’s top three',intro:'Not everything. Just what matters today.',checks:['One thing for my work','One thing for myself','One thing I can leave for tomorrow']},{title:'A little reflection',intro:'Progress isn’t always a straight line.',lines:['Something that felt good','Something I learned','A small win worth noticing']}]},
  parent:{cover:'assets/cover-parent.svg',alt:'Little Beginnings cover: parent cuddling baby on a cloud',label:'EVNOI / LITTLE BEGINNINGS',caption:'Keep all the little firsts.',description:'A home for the moments you’ll want to revisit.',pages:[{title:'Hello, little one',intro:'This is where our story begins.',lines:['The day we met','The first thing I noticed','What I hope you always know']},{title:'Today’s little first',intro:'Every tiny discovery deserves a page.',lines:['Date and place','The moment','How it made us feel']},{title:'A note for later',intro:'The little things I never want to forget.',lines:['Your favourite sound','The way you smile','What our days feel like now']}]}
};
function renderPage(){const info=bookData[state.book],page=info.pages[state.page];$('#pageContent').innerHTML=`<span class="page-head">${state.book==='reset'?'THE 30-DAY RESET':'LITTLE BEGINNINGS'} / 0${state.page+1}</span><span class="page-doodle">${state.book==='reset'?'✳':'☾'}</span><h4>${page.title}</h4><p>${page.intro}</p>${(page.lines||[]).map(x=>`<div class="write-line">${x}</div>`).join('')}${(page.checks||[]).map(x=>`<div class="check-label"><span class="check-box"></span>${x}</div>`).join('')}<span class="tiny-date">EVNOI ✳ &nbsp; 0${state.page+1}</span>`}
function setBook(which){state.book=which;state.page=0;state.bookOpen=false;$('#book').classList.remove('open');$('#coverImage').src=bookData[which].cover;$('#coverImage').alt=bookData[which].alt;$('#bookLabel').textContent=bookData[which].label;$('#bookCaption').textContent=bookData[which].caption;$('#bookDescription').textContent=bookData[which].description;$('#flipButton').innerHTML='Flip open <svg><use href="#arrow"/></svg>';$('#flipButton').setAttribute('aria-expanded','false');$('#nextPage').disabled=true;document.querySelectorAll('.flip-tab').forEach(b=>{let active=b.dataset.book===which;b.classList.toggle('active',active);b.setAttribute('aria-selected',String(active))});renderPage()}
function toggleBook(){state.bookOpen=!state.bookOpen;$('#book').classList.toggle('open',state.bookOpen);$('#flipButton').innerHTML=(state.bookOpen?'Close cover':'Flip open')+' <svg><use href="#arrow"/></svg>';$('#flipButton').setAttribute('aria-expanded',String(state.bookOpen));$('#nextPage').disabled=!state.bookOpen}
function nextPage(){if(!state.bookOpen)return;state.page=(state.page+1)%bookData[state.book].pages.length;$('#pageContent').classList.remove('turning');void $('#pageContent').offsetWidth;$('#pageContent').classList.add('turning');renderPage()}
document.querySelectorAll('.flip-tab').forEach(btn=>btn.addEventListener('click',()=>setBook(btn.dataset.book)));$('#flipButton').addEventListener('click',toggleBook);$('#book').addEventListener('click',toggleBook);$('#book').setAttribute('tabindex','0');$('#book').setAttribute('role','button');$('#book').addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();toggleBook()}});$('#nextPage').addEventListener('click',nextPage);document.querySelectorAll('[data-show-book]').forEach(btn=>btn.addEventListener('click',()=>{setBook(btn.dataset.showBook);$('#flip').scrollIntoView({behavior:'smooth'});setTimeout(()=>{if(!state.bookOpen)toggleBook()},650)}));
const bundles={welcome:{title:'The Welcome Kit',description:'A journal, mini planner, personalised welcome note, bookmark and gift-ready packaging for every new joiner.',tags:['ONBOARDING','CUSTOM INSERTS','BY QUOTE']},reset:{title:'The Team Reset Kit',description:'An undated monthly planner, reflection prompts and a team-intentions card for a new project, offsite or fresh quarter.',tags:['OFFSITES','TEAM RITUALS','BY QUOTE']},appreciation:{title:'The Appreciation Kit',description:'An illustration-led journal, a thoughtful card and optional personalisation to celebrate work worth remembering.',tags:['MILESTONES','APPRECIATION','BY QUOTE']}};
document.querySelectorAll('.bundle-tab').forEach(btn=>btn.addEventListener('click',()=>{const b=bundles[btn.dataset.bundle];document.querySelectorAll('.bundle-tab').forEach(x=>{x.classList.toggle('active',x===btn);x.setAttribute('aria-selected',String(x===btn))});$('#bundleDetail').innerHTML=`<h3>${b.title}</h3><p>${b.description}</p><div class="bundle-tags">${b.tags.map(t=>`<span>${t}</span>`).join('')}</div>`}));
document.addEventListener('click',e=>{let f=e.target.closest('[data-favorite]');if(f){let id=f.dataset.favorite;state.favorites.has(id)?state.favorites.delete(id):state.favorites.add(id);renderProducts();toast(state.favorites.has(id)?'Saved to favourites':'Removed from favourites');return}let interest=e.target.closest('[data-interest]');if(interest){openOverlay('#interestModal');return}let add=e.target.closest('[data-add]');if(add){addToBag(add.dataset.add);return}let open=e.target.closest('[data-open]');if(open){openProduct(open.dataset.open);return}let qty=e.target.closest('[data-qty]');if(qty){let id=qty.dataset.qty;state.bag[id]+=Number(qty.dataset.delta);if(state.bag[id]<1)delete state.bag[id];renderBag();return}let rem=e.target.closest('[data-remove]');if(rem){delete state.bag[rem.dataset.remove];renderBag()}});
$('#productGrid').addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('[data-open]')){e.preventDefault();openProduct(e.target.dataset.open)}});
document.querySelectorAll('.filter').forEach(b=>b.addEventListener('click',()=>{state.filter=b.dataset.filter;document.querySelectorAll('.filter').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b))});renderProducts()}));
$('#bagToggle').addEventListener('click',()=>openOverlay('#bagDrawer'));$('#bagClose').addEventListener('click',closeOverlays);$('#modalClose').addEventListener('click',closeOverlays);$('#interestClose').addEventListener('click',closeOverlays);$('#interestBreakfast').addEventListener('click',()=>openOverlay('#interestModal'));$('#scrim').addEventListener('click',closeOverlays);document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeOverlays();$('#searchPanel').hidden=true;$('#mobileNav').hidden=true;$('#menuToggle').setAttribute('aria-expanded','false')}});
$('#searchToggle').addEventListener('click',()=>{$('#searchPanel').hidden=!$('#searchPanel').hidden;if(!$('#searchPanel').hidden)$('#searchInput').focus()});$('#searchClose').addEventListener('click',()=>{$('#searchPanel').hidden=true;$('#searchInput').value='';state.query='';renderProducts()});$('#searchInput').addEventListener('input',e=>{state.query=e.target.value;renderProducts();if(state.query)$('#shop').scrollIntoView({behavior:'smooth'})});$('#menuToggle').addEventListener('click',()=>{let n=$('#mobileNav');n.hidden=!n.hidden;$('#menuToggle').setAttribute('aria-expanded',String(!n.hidden))});$('#mobileNav').addEventListener('click',e=>{if(e.target.closest('a')){$('#mobileNav').hidden=true;$('#menuToggle').setAttribute('aria-expanded','false')}});
$('#newsletterForm').addEventListener('submit',e=>{e.preventDefault();$('#newsletterMessage').textContent='Preview only—no email was sent or saved. Connect a mailing-list service to enable sign-ups.';$('#newsletterMessage').style.color='#734338';$('#newsletterForm').reset();toast('This concept form is not connected yet')});
renderProducts();renderBag();setBook('reset');
if('IntersectionObserver' in window){const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.08,rootMargin:'0px 0px 40px 0px'});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el))}else document.querySelectorAll('.reveal').forEach(el=>el.classList.add('visible'));
